export declare const usStatesGraph: {
    Washington: string[];
    Oregon: string[];
    California: string[];
    Idaho: string[];
    Nevada: string[];
    Arizona: string[];
    Utah: string[];
    Montana: string[];
    Wyoming: string[];
    Colorado: string[];
    'New Mexico': string[];
    'North Dakota': string[];
    'South Dakota': string[];
    Nebraska: string[];
    Kansas: string[];
    Oklahoma: string[];
    Texas: string[];
    Minnesota: string[];
    Iowa: string[];
    Missouri: string[];
    Arkansas: string[];
    Louisiana: string[];
    Wisconsin: string[];
    Illinois: string[];
    Kentucky: string[];
    Tennessee: string[];
    Mississippi: string[];
    Michigan: string[];
    Indiana: string[];
    Alabama: string[];
    Ohio: string[];
    Georgia: string[];
    Florida: string[];
    'New York': string[];
    Pennsylvania: string[];
    'West Virginia': string[];
    Virginia: string[];
    'North Carolina': string[];
    'South Carolina': string[];
    Vermont: string[];
    Massachusetts: string[];
    'Rhode Island': string[];
    Connecticut: string[];
    'New Jersey': string[];
    Delaware: string[];
    Maryland: string[];
    'New Hampshire': string[];
    Maine: string[];
    Alaska: any[];
    Hawaii: any[];
};
export declare const directedGraph: {
    data: {
        3: number[];
        5: number[];
        1: number[];
        7: number[];
        2: number[];
        4: number[];
        6: number[];
        8: any[];
    };
    getNeighbors: (key: number) => any;
    start: number;
    dest: number;
};
