name: Default

on:
  push:
    branches:
      - "*"

jobs:
  setup-linux:
    name: Setup - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Yarn Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
  test-chromatic:
    name: Test - Chromatic
    runs-on: ubuntu-latest
    needs: setup-linux
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Build
        run: yarn turbo run build --scope=@christianjuth/get-lit --no-deps --include-dependencies
      - name: Test
        run: cd apps/storybook-react/ && yarn chromatic --project-token $CHROMATIC_TOKEN --exit-zero-on-changes --exit-once-uploaded
        env:
          CHROMATIC_TOKEN: ${{ secrets.CHROMATIC_TOKEN }}